name = "projectnewm/newm-market"
version = "1.0.0"
compiler = "v1.1.1"
plutus = "v3"
license = "GPL-3.0-or-later"
description = "Aiken contracts for project NEWM"

[repository]
user = "projectNEWM"
project = "newm-market"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.0.0"
source = "github"

[[dependencies]]
name = "logical-mechanism/assist"
version = "v0.5.0"
source = "github"